
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentification
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      logging:
        level:
          org.springframework.security: trace

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem